-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbwTCB71fQLsKmUbG
KA74PvN44OKBI7OMM8yKyX+vbxWgCgYIKoZIzj0DAQehRANCAAS+Ei2e3/fKParW
rnoJgv9JenmEDlTt0jzIa9HBl+K/pKJC93CLyCQcsxvGf7m3/cPVP7FkguECiv2K
cITmJie3
-----END PRIVATE KEY-----