workflows:
  ios-swift-workflow:
    name: iOS Swift Build
    max_build_duration: 60
    environment:
      vars:
        APP_NAME: "Ornix"
        APP_BUNDLE_ID: "com.romfeminineantic.ornix"
        APP_VERSION: "1.0.0"
        APP_BUILD_NUMBER: "1"
        APPLE_DEVELOPER_TEAM_ID: "V46R39MCS2"
        APPLE_CERTIFICATE_UUID: "225183eb-288e-4318-be45-c85141f06d80"
      xcode: latest
    scripts:
      - name: Skip dependencies
        script: echo "No dependencies to install"
      - name: Build app
        script: |
          xcodebuild -project Ornix.xcodeproj \
                     -scheme Ornix \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $CM_BUILD_DIR/Ornix.xcarchive archive \
                     DEVELOPMENT_TEAM=$APPLE_DEVELOPER_TEAM_ID
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/Ornix.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/*.ipa
